[package]
name = "cs4240"
version = "0.1.0"
authors = ["Christopher Tam <christophertam@gatech.edu>", "Dhruv Mehra <dmehra6@gatech.edu"]

[dependencies]
regex = "~0.2"
clap = "2.30.0"
lazy_static = "1.0"
serde_json = "1.0"